### ISSUE TITLE
How to insert sqrtm into CNN model forward()?

### ISSUE THREAD

**Issue by hcygeorge** [steveli/pytorch-sqrtm#1]
I inserted sqrtm in the forward pass of CNN model, using feature map as input.
But it return error that sqrtm is in device cpu, and simply add .cuda() after sqrtm didn't work.
I am thinking about how to put sqrtm in  CNN model forward() properly?

**Comment by steveli** [comment]
Hi. I just pushed an update that can work with CUDA tensors. Note that the core computation of this implementation is done on CPU using scipy.
